project:
  output-dir: docs
  
  preview: 
    port: 6532
    browser: true
    watch-inputs: true
    navigate: true
  
author:
  - name: Cormac Monaghan
    orcid: 0000-0001-9012-3060
    email: cormac.monaghan@mu.ie
    affiliations: Hamilton Institute, Maynooth University

format: 
  clean-revealjs:
    footer: |
      These slides were built with [{{< fa brands github title="GitHub octocat logo" >}}](https://c-monaghan.github.io/), [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target="_blank"}, and [Quarto](https://quarto.org/){target="_blank"}
    self-contained: true
    
bibliography: ./files/references.bib
csl: ./files/apa-sup.csl
citations-hover: true
citeproc: true